### ISSUE TITLE
java.lang.SecurityException: Caller no longer running

### ISSUE THREAD

**Issue by divergentdave** [divergentdave/Transparensbee#29]
New crash report who dis

Edit:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Caller no longer running
	at android.os.Parcel.readException(Parcel.java:1942)
	at android.os.Parcel.readException(Parcel.java:1888)
	at android.app.job.IJobCallback$Stub$Proxy.completeWork(IJobCallback.java:218)
	at android.app.job.JobParameters.completeWork(JobParameters.java:220)
	at android.support.v4.app.JobIntentService$JobServiceEngineImpl$WrapperWorkItem.complete(JobIntentService.java:254)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:365)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:354)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by divergentdave** [comment]
The crash message is now showing up in search results. See https://github.com/evernote/android-job/issues/255 and https://issuetracker.google.com/issues/63622293. No resolution yet, though.

Edit: The issue on Google's support library issue tracker doesn't have the same message, but it could be related.

**Comment by divergentdave** [comment]
I haven't encountered this after upgrading to Android Oreo, so I'm going to close this under the assumption that the problem was in either the beta version of the OS or the beta version of the support library, and the production version of whichever fixed the problem.
